### ISSUE TITLE
Titanium SDK 6.0 recompile

### ISSUE THREAD

**Issue by dave101** [trevorf/ti-android-streamer#18]
Is it possible to get a recompile under Titanium SDK 6.0 as all modules now require a recompile to function?

I have tried building the module myself but get the following compile errors:

    [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:345:1: error: expected unqualified-id before 'using'
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:362:33: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:369:51: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:373:29: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:441:25: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: At global scope:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:481:1: error: expected unqualified-id before 'using'
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:484:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:667:49: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:668:43: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:844:26: error: expected ',' or '...' before '&&' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:844:34: error: invalid constructor; you probably meant 'v8::Global<T> (const v8::Global<T>&)'
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:852:40: error: expected ',' or '...' before '&&' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:874:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:875:35: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In constructor 'v8::Global<T>::Global()':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:820:42: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:854:18: error: 'rhs' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:857:18: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'v8::Global<T> v8::Global<T>::Pass()':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:864:44: error: expected '>' before '&&' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:864:44: error: expected '(' before '&&' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:864:46: error: expected identifier before '>' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:864:54: error: expected ')' before ';' token
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: At global scope:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:882:1: error: expected unqualified-id before 'using'
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:1119:10: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:1125:30: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:2104:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:2314:42: error: 'v8::NewStringType' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:2315:48: error: 'v8::NewStringType' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:2645:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:3271:36: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: At global scope:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:3449:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:3533:38: error: 'ArrayBufferCreationMode' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:3896:38: error: 'ArrayBufferCreationMode' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4488:57: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4504:57: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4574:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4596:36: error: 'PropertyHandlerFlags' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4624:36: error: 'PropertyHandlerFlags' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'void v8::ObjectTemplate::SetIndexedPropertyHandler(v8::IndexedPropertyGetterCallback, v8::IndexedPropertySetterCallback, v8::IndexedPropertyQueryCallback, v8::IndexedPropertyDeleterCallback, v8::IndexedPropertyEnumeratorCallback, v8::Local<v8::Value>)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:4756:77: error: the default argument for parameter 6 of 'v8::IndexedPropertyHandlerConfiguration::IndexedPropertyHandlerConfiguration(v8::IndexedPropertyGetterCallback, v8::IndexedPropertySetterCallback, v8::IndexedPropertyQueryCallback, v8::IndexedPropertyDeleterCallback, v8::IndexedPropertyEnumeratorCallback, v8::Local<v8::Value>, v8::PropertyHandlerFlags)' has not yet been parsed
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: At global scope:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:5095:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:5388:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:5424:35: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:5424:35: error: 'virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()' declared virtual cannot be defaulted in the class body
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:7530:7: error: 'nullptr' was not declared in this scope
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h: In member function 'void v8::Template::Set(v8::Isolate*, char const*, v8::Local<v8::Data>)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/v8.h:7999:46: error: 'NewStringType' is not a class or namespace
     [exec] In file included from jni/com.woohoo.androidaudiostreamer.AndroidaudiostreamerModule.cpp:18:0:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/TypeConverter.h: At global scope:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/TypeConverter.h:20:97: error: '>>' should be '> >' within a nested template argument list
     [exec] In file included from jni/com.woohoo.androidaudiostreamer.AndroidaudiostreamerModule.cpp:19:0:
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h: In function 'void titanium::SetMethod(v8::Isolate*, v8::Local<v8::Object>, char const*, v8::FunctionCallback)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h:101:38: error: 'v8::NewStringType' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h: In function 'void titanium::SetProtoMethod(v8::Isolate*, v8::Local<v8::FunctionTemplate>, char const*, v8::FunctionCallback)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h:117:38: error: 'v8::NewStringType' is not a class or namespace
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h: In function 'void titanium::SetTemplateMethod(v8::Isolate*, v8::Local<v8::FunctionTemplate>, char const*, v8::FunctionCallback)':
     [exec] /Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/android/native/include/V8Util.h:131:38: error: 'v8::NewStringType' is not a class or namespace
     [exec] make: *** [/var/folders/8z/d1dyhsfn5p1fxwcfxy1432fh0000gn/T//davidr/androidaudiostreamer-generated/obj/local/armeabi/objs/com.woohoo.androidaudiostreamer/com.woohoo.androidaudiostreamer.AndroidaudiostreamerModule.o] Error 1

BUILD FAILED
/Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:347: The following error occurred while executing this line:
/Users/davidr/Library/Application Support/Titanium/mobilesdk/osx/6.0.0.GA/module/android/build.xml:302: exec returned: 2

**Comment by AppWerft** [comment]
same problem. Who can solve it?

**Comment by furthurr** [comment]
This module work on 7.5.x ...
[com.woohoo.androidaudiostreamer-android-1.7.3.zip](https://github.com/trevorf/ti-android-streamer/files/2929303/com.woohoo.androidaudiostreamer-android-1.7.3.zip)
